In [1]:
import numpy as np

#### 예시, 몸무게, 키, 흡연유무를 변수로 하는 수명 추정

In [3]:
# coefficients matrix A and a vector b
A = np.array([[60, 5.5, 1], [65, 5.0, 0], [55, 6.0, 1]])
b = np.array([66, 74, 78])

In [6]:
# identity matrix(항등행렬)
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# computing an inverse(역행렬)
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [16]:
# 잘못된 행렬곱
A * A_inv # 내적이 아니다. 단순히 행렬의 동일한 위치간 곱셈

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [27]:
# 행렬곱
print(A.dot(A_inv).round(1))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


#### 역행렬을 활용한 해 구하기

In [23]:
# solution of a linear system
x = A_inv.dot(b)
x

array([ -0.4,  20. , -20. ])

In [25]:
# 선형시스템을 풀기 위한 numpy 기능
x = np.linalg.solve(A, b)
x

array([ -0.4,  20. , -20. ])